version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management

  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    depends_on:
      - rabbitmq
  clientapp:
    image: clientapp
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    depends_on:
      - rabbitmq
      - basketapi

